[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
grid = "*"
regex = "*"
itertools = "*"
rayon = "*"
cached = "*"
nalgebra = "*"
lazy_static = "*"

[[bin]]
name = "active"
path = "src/day_25.rs"
